# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GroupedControllerDismissalDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'GroupedControllerDismissal', :path => '..'

  # Pods for GroupedControllerDismissalDemo

  target 'GroupedControllerDismissalDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GroupedControllerDismissalDemoUITests' do
    # Pods for testing
  end

end
